# Usa Node 20
FROM node:20

# Directorio de trabajo dentro del contenedor
WORKDIR /server

# Copiar archivos del backend (ya incluye client-build)
COPY . .

# Instalar dependencias del backend
RUN npm install

# Exponer el puerto que usa tu app
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["node", "index.js"]
